// <auto-generated />
using EstudoCRUDAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstudoCRUDAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstudoCRUDAPI.Models.ECV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ECVs");
                });

            modelBuilder.Entity("EstudoCRUDAPI.Models.Vistoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ECVId")
                        .HasColumnType("int");

                    b.Property<int>("OS")
                        .HasColumnType("int");

                    b.Property<string>("nomeVistoriador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("statusVistoria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ECVId");

                    b.ToTable("Vistorias");
                });

            modelBuilder.Entity("EstudoCRUDAPI.Models.Vistoria", b =>
                {
                    b.HasOne("EstudoCRUDAPI.Models.ECV", "ECV")
                        .WithMany()
                        .HasForeignKey("ECVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ECV");
                });
#pragma warning restore 612, 618
        }
    }
}
